name: Client Deployment

on:
  push:
    branches: [main]
    paths:
      - "client/**"
  workflow_dispatch:

jobs:
  deploy-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Deploy Client
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -e
            # Install Node.js and npm if not present
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
              apt-get install -y nodejs
            fi

            # Kill existing process if running
            pkill -f "npm run preview" || true

            cd /root/jogo-de-nave/client
            git pull origin main

            # Clear npm cache and node_modules if there are issues
            rm -rf node_modules package-lock.json
            npm cache clean --force

            # Install dependencies and build
            npm install
            npm run build
            npm run preview
